name: test_color
description: "Color changing app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-11.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  solid_lints: ^0.0.19

flutter:
  uses-material-design: true
